tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Modern replacement for 'ls'
brew "exa"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Command-line fuzzy finder written in Go
brew "fzf"
# Mac App Store command-line interface
brew "mas"
# Open source relational database management system
brew "mysql", restart_service: true
# Fast, highly customisable system info script
brew "neofetch"
# General-purpose scripting language
brew "php", restart_service: true
cask "dozer"
cask "rectangle"
mas "Enpass", id: 732710998
mas "Telegram", id: 747648890
